<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX5rygj9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX5rygj9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX5rygj9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX5rygj9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX5rygj9\appProdProjectContainer(array(
    'container.build_hash' => 'X5rygj9',
    'container.build_id' => 'e4e2f0ca',
    'container.build_time' => 1537460900,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX5rygj9');
